### PR TITLE
Pyramid WFS 

### PR DESCRIPTION
**Pull request by AurelieMagniez**
Add a new version of the Pyramid WFS (PWS),  change the conf parse file to add more input parameters for the PWS. 
Add a new conf file example to run a PWS

### CODE REVIEW

**Comment by andrewpaulreeves** [comment]
Hi @AurelieMagniez - looks really good! 

2 Small points:
 - you have a "photons per mag" type function in teh pyramid WFS module. Is this something that can be imported from aotools, or put in a seperate library so it might be useful elsewhere?
 - Could you add a very quick test in the "tests" directory, that loads your WFS, runs it and if your feeling really ambitious, checks against some known phase / measurement?

**Comment by ojdf** [comment]
as far as I can see, the `photons_per_mag` is not actually used anywhere so can probably be removed?

**Comment by AurelieMagniez** [comment]
Hi both,

Yes, the `photon_per_mag` is a function I left because I am using photon counting in my project. I forgot to delete it for this release, unless people are interested in photon counting?

As for the tests, do you want me to do something on the model of "testWfs.py"?

**Comment by andrewpaulreeves** [comment]
All looks good!

**Pull request merged**
